# CMake generated Testfile for 
# Source directory: /home/rehan-10xe/Documents/work/llama.cpp-RISE-testing
# Build directory: /home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/build-riscv-cross
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test-quantize "sh" "-c" "QEMU_CPU=\"\${QEMU_CPU:-rv64,v=true,vlen=512,zfh=true,zvfh=true,zifencei=true,vext_spec=v1.0}\" exec /home/rehan-10xe/Downloads/riscv64-glibc-ubuntu-22.04-llvm-nightly-2024.08.03-nightly/riscv/bin/qemu-riscv64 -L /home/rehan-10xe/Downloads/riscv64-glibc-ubuntu-22.04-gcc/riscv/sysroot \"\$0\" \"\$@\"" "/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/build-riscv-cross/bin/test-quantize" "--size" "256" "--size" "512" "--size" "1024" "--size" "2048" "--size" "5632")
set_tests_properties(test-quantize PROPERTIES  _BACKTRACE_TRIPLES "/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/CMakeLists.txt;45;add_test;/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/CMakeLists.txt;73;add_rise_test;/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/CMakeLists.txt;0;")
add_test(test-float "sh" "-c" "QEMU_CPU=\"\${QEMU_CPU:-rv64,v=true,vlen=512,zfh=true,zvfh=true,zifencei=true,vext_spec=v1.0}\" exec /home/rehan-10xe/Downloads/riscv64-glibc-ubuntu-22.04-llvm-nightly-2024.08.03-nightly/riscv/bin/qemu-riscv64 -L /home/rehan-10xe/Downloads/riscv64-glibc-ubuntu-22.04-gcc/riscv/sysroot \"\$0\" \"\$@\"" "/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/build-riscv-cross/bin/test-float" "--size" "256" "--size" "512" "--size" "1024" "--size" "2048" "--size" "5632")
set_tests_properties(test-float PROPERTIES  _BACKTRACE_TRIPLES "/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/CMakeLists.txt;45;add_test;/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/CMakeLists.txt;74;add_rise_test;/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/CMakeLists.txt;0;")
add_test(test-repack "sh" "-c" "QEMU_CPU=\"\${QEMU_CPU:-rv64,v=true,vlen=512,zfh=true,zvfh=true,zifencei=true,vext_spec=v1.0}\" exec /home/rehan-10xe/Downloads/riscv64-glibc-ubuntu-22.04-llvm-nightly-2024.08.03-nightly/riscv/bin/qemu-riscv64 -L /home/rehan-10xe/Downloads/riscv64-glibc-ubuntu-22.04-gcc/riscv/sysroot \"\$0\" \"\$@\"" "/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/build-riscv-cross/bin/test-repack" "--m" "1,256" "--k" "256" "--n" "2048" "--threads" "8")
set_tests_properties(test-repack PROPERTIES  _BACKTRACE_TRIPLES "/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/CMakeLists.txt;45;add_test;/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/CMakeLists.txt;76;add_rise_test;/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/CMakeLists.txt;0;")
add_test(test-quantize-perf "sh" "-c" "QEMU_CPU=\"\${QEMU_CPU:-rv64,v=true,vlen=512,zfh=true,zvfh=true,zifencei=true,vext_spec=v1.0}\" exec /home/rehan-10xe/Downloads/riscv64-glibc-ubuntu-22.04-llvm-nightly-2024.08.03-nightly/riscv/bin/qemu-riscv64 -L /home/rehan-10xe/Downloads/riscv64-glibc-ubuntu-22.04-gcc/riscv/sysroot \"\$0\" \"\$@\"" "/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/build-riscv-cross/bin/test-quantize-perf")
set_tests_properties(test-quantize-perf PROPERTIES  WORKING_DIRECTORY "/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/build-riscv-cross" _BACKTRACE_TRIPLES "/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/CMakeLists.txt;65;add_test;/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/CMakeLists.txt;79;add_root_ctest;/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/CMakeLists.txt;0;")
add_test(test-backend-ops-mul-mat "sh" "-c" "QEMU_CPU=\"\${QEMU_CPU:-rv64,v=true,vlen=512,zfh=true,zvfh=true,zifencei=true,vext_spec=v1.0}\" exec /home/rehan-10xe/Downloads/riscv64-glibc-ubuntu-22.04-llvm-nightly-2024.08.03-nightly/riscv/bin/qemu-riscv64 -L /home/rehan-10xe/Downloads/riscv64-glibc-ubuntu-22.04-gcc/riscv/sysroot \"\$0\" \"\$@\"" "/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/build-riscv-cross/bin/test-backend-ops" "test" "-o" "MUL_MAT" "-b" "CPU" "-p" "(^|,)m=([2-9]|[1-9][0-9]+)(,|\$)")
set_tests_properties(test-backend-ops-mul-mat PROPERTIES  WORKING_DIRECTORY "/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/build-riscv-cross" _BACKTRACE_TRIPLES "/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/CMakeLists.txt;65;add_test;/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/CMakeLists.txt;82;add_root_ctest;/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/CMakeLists.txt;0;")
add_test(test-backend-ops-flash-attn "sh" "-c" "QEMU_CPU=\"\${QEMU_CPU:-rv64,v=true,vlen=512,zfh=true,zvfh=true,zifencei=true,vext_spec=v1.0}\" exec /home/rehan-10xe/Downloads/riscv64-glibc-ubuntu-22.04-llvm-nightly-2024.08.03-nightly/riscv/bin/qemu-riscv64 -L /home/rehan-10xe/Downloads/riscv64-glibc-ubuntu-22.04-gcc/riscv/sysroot \"\$0\" \"\$@\"" "/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/build-riscv-cross/bin/test-backend-ops" "test" "-o" "FLASH_ATTN_EXT" "-b" "CPU")
set_tests_properties(test-backend-ops-flash-attn PROPERTIES  WORKING_DIRECTORY "/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/build-riscv-cross" _BACKTRACE_TRIPLES "/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/CMakeLists.txt;65;add_test;/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/CMakeLists.txt;86;add_root_ctest;/home/rehan-10xe/Documents/work/llama.cpp-RISE-testing/CMakeLists.txt;0;")
subdirs("llama.cpp")
